### ISSUE TITLE
Documentation contains 'dns_enabled', which doesn't exist

### ISSUE THREAD

**Issue by gregberns** [jenkins-x/terraform-azurerm-jx#17]
The ReadMe table of module properties  states that there should be a `dns_enabled` property which "Flag which sets whether a DNS zone is provisioned or not". It does not appear that property exists on the top level module, and there is an error when it is used in a script.

```
Error: Unsupported argument

  on app-int/main.tf line 139, in module "aks-jx":
 139:   dns_enabled  = true

An argument named "dns_enabled" is not expected here.
````

**Comment by chrismellard** [comment]
Closed by #19
