### ISSUE TITLE
Create CI scripts

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/terraform-azurerm-jx#2]
We want to test the correctness and validity of the Terraform modules per provider on each PR in this repository.

There will need to be a script for AKS that will run its Terraform module, create a cluster and any necessary resources, and validate that everything was created correctly based on the parameters that were passed and the state that was created.

**Comment by helayoty** [comment]
@dgozalo may we add this to the azure github project https://github.com/orgs/jenkins-x/projects/9

**Comment by chrismellard** [comment]
Should be closed by #15

**Comment by chrismellard** [comment]
CI scripts merged iin #15 so closing
