### ISSUE TITLE
Docs: Add note about the `MC_...` resource group

### ISSUE THREAD

**Issue by gregberns** [jenkins-x/terraform-azurerm-jx#20]
It was very confusing when ran the JenkinsX Terraform project for the first time and saw a `MC_myResourceGroup_myAKSCluster_eastus` resource group created. I thought it was a bug in the terraform-azurerm-jx project because I didn't specify that naming!

Just a suggestion - Add links to the documentation that notify users that the second resource group will be created automatically as part of the Azure process. (Feel free to close this if you don't feel it would provide value)

Here are two links that could be provided:

[Why are two resource groups created with AKS?](https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks)

[Can I provide my own name for the AKS node resource group?](https://docs.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group)

**Comment by chrismellard** [comment]
Opened PR that specifies the node resource group as a parameter which provides more clarity hopefully
