### ISSUE TITLE
If enable_tls is set, require tls_email

### ISSUE THREAD

**Issue by gregberns** [jenkins-x/terraform-azurerm-jx#22]
## Summary

If the Terraform module defines `enable_tls = true` (default is false), but the`tls_email` setting is not configured, then when `jx boot` is run on the resulting `jx-requirements.yml` file, then the following error will occur.

```
STEP: create-install-values command: /bin/sh -c jx step create install values -b in dir: /Users/gb/github/issaonline/gitops-k8s-dev/jenkins-x-boot-config/env

WARNING: Note that we have only tested TLS support on Google Container Engine with external-dns so far. This may not work!
error: You must provide a valid email address to enable TLS so you can receive notifications from LetsEncrypt about your certificates: mail: no address
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b' command in directory 'env', output: ''
```

## Proposed Change

If `enable_tls = true` is set, then the `tls_email` property should be required in the Terraform script.

**Comment by chrismellard** [comment]
So even with Terraform 0.13 we can't do variable validation dependent on other variables. Best I think we can do is to update  the  Readme highlighting that if `enable_tls` is set that `tls_email` is a required property.

@ankitm123 Any ideas or are we tackling this variable dependency problem over in the  other terraform repos?

**Comment by ankitm123** [comment]
@chrismellard Nope, nothing like that is done for the eks module. But I found this on reddit (👅 ), which could be handy - https://www.reddit.com/r/Terraform/comments/ilavfw/make_input_variable_required_if_another_one_is_set/ (2nd comment from apparentlymart - a core terraform developer).

**Comment by chrismellard** [comment]
Thanks. Ends up looking something like this
```
variable "tls" {
  type = object(
    {
      enable_tls = string,
      email      = string
    }
  )

  default = {
    enable_tls = false
    email      = ""
  }
  validation {
    condition = (
      (var.tls.enable_tls && length(var.tls.email) > 0)
      || ! var.tls.enable_tls

    )
    error_message = "If tls.enable_tls is set to true then tls.email must be specified"
  }

}
```

**Comment by ankitm123** [comment]
yeah
