### ISSUE TITLE
Creation of Hashicorp's Vault resources with Terraform scripts for AKS

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/terraform-azurerm-jx#3]
# Summary
The resources needed by Vault to work in Azure / AKS need to be created by Terraform before running `jx boot` for the cluster.

The creations of these resources should be conditional and based on a variable passed to the Terraform execution.

This issue should replace https://github.com/jenkins-x/jx/issues/5057 as we are moving to externalizing the creation of resources out of the Jenkins-x code.

An example Vault module for EKS can be found here: 

https://github.com/jenkins-x/jx-cloud-provisioners/tree/master/eks/terraform/vault

Note that those are the resources needed to run Vault in AWS, refer to Vault's official documentation to get an idea of which resources  Vault will need to work in Azure.

Ideally, the creation of Vault resources should be done in its own module as seen here:

https://github.com/jenkins-x/jx-cloud-provisioners/tree/master/eks/terraform/vault

# Acceptance Criteria
A Terraform module to create any resources that Hashicorp's Vault will need to run in Azure / AKS.

**Comment by helayoty** [comment]
@ams0 will start looking on this one

**Comment by chrismellard** [comment]
#14 should hopefully close this issue. There's a PR required on jenkins-x/jx#7544 to get the jx side working.

**Comment by chrismellard** [comment]
Both the above PRs have now been merged so closing
