### ISSUE TITLE
jx boot - Additional property azure is not allowed in vault

### ISSUE THREAD

**Issue by peter-poki** [jenkins-x/terraform-azurerm-jx#30]
Hello,

Thanks for the module, works like a charm. I created cluster on Azure, everything seems to be in order, but when I try to use jx-requirements.yml with jx boot I get following error:
```
WARNING: validation failures in YAML file ~/jenkins-x-boot-config/jx-requirements.yml: vault: Additional property azure is not allowed
error: unable to load jx-requirements.yml: validation failures in YAML file ~/jenkins-x-boot-config/jx-requirements.yml:
vault: Additional property azure is not allowed
```

I looked into banzai vault operator, it seems to support Azure Key Vault. But when I looked into jx docs I see message
**The Bank-Vaults operator is currently only supported with GKE or EKS.**, see here: https://jenkins-x.io/docs/reference/components/vault/

Do you have some **beta** version of jx, where jx boot command works with azure vault?

Or should I open issue on jx?

Thank you

**Comment by peter-poki** [comment]
https://github.com/jenkins-x/jx/pull/7544

I found your pull request, had to download **prerelease** version, will test it tomorrow and let you know

**Comment by peter-poki** [comment]
So with using prerelease version of jx, I was able to move forward, but got stucked on this error with vault creation: **503 Service Temporarily Unavailable**.

So my vault stetefulset isn't initialized correclty:
```
$ kubectl logs -n jx jx-vault-asptstsmashin-0 -c bank-vaults
time="2020-09-09T07:45:18Z" level=info msg="initializing vault..."
time="2020-09-09T07:45:18Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :9091
time="2020-09-09T07:45:22Z" level=fatal msg="error initializing vault: error testing if vault is initialized: Get http://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: connect: connection refused"
```

Do you have any idea why, or should I open issue on banzaicloud/vault?

**Comment by chrismellard** [comment]
Just looks like vault isn't initialised correctly. Have you set the vault storage secret on the command line before running `jx boot`? I recently added this in to the README that a specific env var is required in order for vault to be configured correctly.
Relevant part of README here - 
https://github.com/jenkins-x/terraform-azurerm-jx/blob/master/README.md#jx-boot-environment-secrets

**Comment by chrismellard** [comment]
FWIW - I think this passing of secrets via CLI is sub-optimal. Hopefully in the future we move to storing secrets within the cluster that can be picked up by `jx boot`

**Comment by peter-poki** [comment]
Yes, exposing ENV_VARS helped, thank you.

Wouldn't it be possible, to configure Vault with secret_ref, and create this secret using kubectl provider?

Thanks

P.S. Issue can be closed.

**Comment by chrismellard** [comment]
There will be further changes  in this space in jx3 to optimise how these secret details are passed between terraform and jx to make it more zero touch
