### ISSUE TITLE
Enable and configure Managed Identities for the AKS cluster using Terraform

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/terraform-azurerm-jx#4]
# Summary
Similar to what we do for EKS and are preparing for GKE, we want to define fine grained permissions for any cluster where Jenkins X will be installed.

An example for EKS can be found in the Jenkins-x module, here:

https://github.com/jenkins-x/jx-cloud-provisioners/blob/master/eks/terraform/jenkins-x/irsa.tf

Here we create IAM Policies and IAM Roles that will be used to annotate Kubernetes `Service Accounts` so any pod using these `Service Accounts` can assume the roles.

The idea is to configure the AKS cluster to use `Managed Identities` an have an easy way to define new Service Accounts and permissions.

For now, the `Service Account` being configured with IAM permissions should be:

 * tekton-bot: This is the `Service Account` that the pods running the builds use. The necessary permissions will be defined later.

# Acceptance Criteria
Configure the AKS cluster to use `Managed Identities` and define an easy way to create and configure new `Service Accounts` with the necessary permissions.

**Comment by hferentschik** [comment]
This might be relevant in this context:

- https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity
- https://github.com/Azure/aad-pod-identity

**Comment by chrismellard** [comment]
Just been looking in to this with regards to setting up Velero service accounts. Currently the fine-grained authorisation to Azure RM APIs is handled via the aad-pod-identity project. This attaches identities to pods directly using its CRDs and not service accounts. So the approach I've seen being used in GKE with service account annotations probably isn't going to work immediately here. For the Velero use case that I'm going to raise a separate ticket for this the aad-pod-identity can be used as the Azure Velero plug-in is MSI aware.
Feels like some more work required with AKS and its satellite open source projects to get service accounts associated with external identity contexts unless I'm missing something.

**Comment by helayoty** [comment]
/area/aks

**Comment by chrismellard** [comment]
Closed by #34
