### ISSUE TITLE
Create a jx-requirements.yml template and generate a valid file after running the Terraform AKS script

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/terraform-azurerm-jx#5]
# Summary 

The `jx-requirements.yml` file is the way to configure how we want to install Jenkins X in a cluster using `jx boot`.

An example of a base one, for GKE, can be found here:

https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/jx-requirements.yml

With Terraform, you can define a template that will be filled with information from the resources created by Terraform.

The idea is to generate a valid `jx-requirements-aks.yml` file with the Azure resources and necessary configuration being already written in it so you can just `jx boot -r jx-requirements-aks.yml` and make it work without modifying anything. 

An example for the template being used for EKS can be found here:
https://github.com/jenkins-x/jx-cloud-provisioners/blob/master/eks/terraform/jenkins-x/jx-requirements.yml.tpl

And how to configure and create the final file:

https://github.com/jenkins-x/jx-cloud-provisioners/blob/master/eks/terraform/main.tf#L119-L145

# Acceptance Criteria

A valid `jx-requirements-aks.yml` file being generated after Terraform successfully runs.

**Comment by chrismellard** [comment]
/assign @chrismellard 

Currently working on this and just spotted this ticket, wip PR here #9

**Comment by chrismellard** [comment]
Think this can be closed now as multiple PRs have recently added to generating to a jx-requirements file that does successfully boot a cluster.
